/* ============================================================
 * 特变电工“双中心” 65+ 项管控指标字典与定义
 * 数据来源：《“双中心”项目能碳管控指标体系V1.4.xlsx》
 * ============================================================ */

export type IndicatorStatus = '优秀' | '正常' | '异常'

export type Indicator = {
  id: number
  name: string
  definition: string
  formula: string
  desc: string
  unit: string
  center: '集控' | '集采'
  category: string
  source: string
  scope: string
  freq: string
  factory?: string
  current: number
  base: number
  target: number
  yoyDiff?: number
  yoyRate?: number
  momDiff?: number
  momRate?: number
  status: IndicatorStatus
  aiReasoning?: string
}

export const indicators: Indicator[] = [
  {
    id: 1,
    name: '产品碳足迹',
    definition: '引用 GB/T 24067、ISO14067，主要管理摇篮到大门阶段的产品碳足迹值',
    formula: '实时数据：取产品碳足迹核算值',
    desc: '来源于本地产品碳足迹追踪及报告系统的产品碳足迹数据',
    unit: 'tCO2/台套',
    center: '集采',
    category: '碳排放',
    source: '股份要求（应对 CBAM 与绿色招采）',
    scope: '全产品',
    freq: '实时/工单',
    factory: '沈变本部',
    current: 12.68,
    base: 13.2,
    target: 12.0,
    yoyDiff: -0.52,
    yoyRate: -3.94,
    status: '优秀',
    aiReasoning: '供应链上游铜铝原材料绿色采购比例上升 15%，带动单台碳足迹下降。',
  },
  {
    id: 2,
    name: '开展产品碳足迹分析占比',
    definition: '统计期内开展主要产品碳足迹分析的产品类别数量占主要产品类别总数的比值',
    formula: 'Rcf = (Ncf / N) * 100%',
    desc: '产品碳足迹系统提供开展计算的种类明细，从 ERP 获取全部产品明细',
    unit: '%',
    center: '集采',
    category: '碳排放',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 65.4,
    base: 60.0,
    target: 80.0,
    yoyDiff: 5.4,
    yoyRate: 9.0,
    status: '正常',
  },
  {
    id: 3,
    name: '综合能源消费量',
    definition: '统计期内组织综合能源消费的总吨标准煤 (tce)',
    formula: 'E = ∑(Ei * ki)，电力折标系数采用当量值 (0.1229 kgce/kWh)',
    desc: '涵盖电、天然气、蒸汽、热力、柴油、汽油等所有能源介质',
    unit: 'tce',
    center: '集控',
    category: '综合能耗',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 1284.5,
    base: 1320.0,
    target: 1250.0,
    yoyDiff: -35.5,
    yoyRate: -2.69,
    status: '正常',
    aiReasoning: '本月错峰用电管理推进顺利，公辅空压机联控节能运行降低损耗 4.2%。',
  },
  {
    id: 4,
    name: '总碳排放量',
    definition: '指统计期内企业组织产生的二氧化碳总排放量 (tCO2)',
    formula: 'C = C燃烧 + C过程 + C购入电 - C输出电 + C购入热 - C输出热 - C回收',
    desc: '重点核算能源活动碳排放，电力排放取省级电网平均排放因子',
    unit: 'tCO2',
    center: '集控',
    category: '碳排放',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 3420.8,
    base: 3600.0,
    target: 3300.0,
    yoyDiff: -179.2,
    yoyRate: -4.98,
    status: '优秀',
    aiReasoning: '自建屋顶分布式光伏消纳电量提升 12%，抵消部分市电购电碳排放。',
  },
  {
    id: 5,
    name: '单位能耗碳排放',
    definition: '统计期内每消费一吨标准煤产生的二氧化碳排放量',
    formula: 'I = C / E (电力折标按等价值计算，优先使用省平均发电煤耗)',
    desc: '分子与分母核算范围保持严格一致',
    unit: 'tCO2/tce',
    center: '集控',
    category: '碳排放',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 2.66,
    base: 2.72,
    target: 2.55,
    yoyDiff: -0.06,
    yoyRate: -2.21,
    status: '正常',
  },
  {
    id: 6,
    name: '非化石能源消费占比',
    definition: '统计期内非化石能源消费量与综合能源消费量的比值',
    formula: 'r = (R / E) * 100% (交易绿电、绿证可纳入分子)',
    desc: '自建分布式绿电 + 外部交易绿电 + 绿证认购',
    unit: '%',
    center: '集控',
    category: '绿电与非化石',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 38.6,
    base: 32.0,
    target: 40.0,
    yoyDiff: 6.6,
    yoyRate: 20.63,
    status: '优秀',
    aiReasoning: '月度新完成 500 万 kWh 绿电交易结算，非化石消费显著提升。',
  },
  {
    id: 7,
    name: '非化石电力物理认定量占比',
    definition: '具备物理可溯源条件的非化石能源电力消费量占同期总用电量的比值',
    formula: 'Eui = (Ez / Q) * 100% (交易绿电/绿证不计入分子)',
    desc: '仅包含厂区自建光伏消纳电量与专线直供可物理溯源绿电',
    unit: '%',
    center: '集控',
    category: '绿电与非化石',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 24.8,
    base: 22.0,
    target: 30.0,
    yoyDiff: 2.8,
    yoyRate: 12.73,
    status: '正常',
  },
  {
    id: 8,
    name: '单位工业增加值能耗',
    definition: '统计期内综合能源消费量与企业工业增加值的比值',
    formula: 'Enva = E / Gnva (Gnva: 工业增加值，万元)',
    desc: '月度依据财务数据估算，年度重新统一汇算',
    unit: 'tce/万元',
    center: '集控',
    category: '单位产值能耗',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度/年度',
    factory: '沈变本部',
    current: 0.142,
    base: 0.155,
    target: 0.135,
    yoyDiff: -0.013,
    yoyRate: -8.39,
    status: '优秀',
  },
  {
    id: 9,
    name: '节能装备应用占比',
    definition: '达到或优于能效国标2级水平的装备额定总功率占纳入范围总功率比例',
    formula: 'S = (Res / Ets) * 100%',
    desc: '包括变压器、电动机、工业锅炉、风机、空压机、热泵等',
    unit: '%',
    center: '集控',
    category: '能效与装备',
    source: '国家级零碳工厂要求',
    scope: '工厂级',
    freq: '月度增量',
    factory: '沈变本部',
    current: 78.5,
    base: 72.0,
    target: 85.0,
    yoyDiff: 6.5,
    yoyRate: 9.03,
    status: '正常',
  },
  {
    id: 10,
    name: '关键能源数据自动采集率',
    definition: '进出用能单位、次级单位和主要用能设备(≥45kW)能源数据自动采集比例',
    formula: 'Rp = (Ns / Nl) * 100% (Ns: 有效自动采集表数, Nl: 理论应装表数)',
    desc: '依据特变电工计量管理标准 TBEA-BA-6.5.2.1.1 考核',
    unit: '%',
    center: '集控',
    category: '能效与装备',
    source: '股份管理要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 94.2,
    base: 88.0,
    target: 95.0,
    yoyDiff: 6.2,
    yoyRate: 7.05,
    status: '优秀',
  },
  {
    id: 11,
    name: '单位产值能耗',
    definition: '统计期内综合能源消费量与产品产值的比值',
    formula: 'g = E / G (G: 产品产值，万元)',
    desc: '变压器产值取经营日报管理系统，线缆产值取大数据平台',
    unit: 'tce/万元',
    center: '集控',
    category: '单位产值能耗',
    source: '股份管理要求',
    scope: '工厂级',
    freq: '月度',
    factory: '沈变本部',
    current: 0.118,
    base: 0.125,
    target: 0.110,
    yoyDiff: -0.007,
    yoyRate: -5.6,
    status: '正常',
  },
  {
    id: 12,
    name: '单位产品能耗（型号）',
    definition: '统计期内该产品型号综合能源消费量与产品产量的比值',
    formula: 'e = E / M (M: 产品产量，万kVA 或 万km*mm²)',
    desc: '按订单提取产量，关键工序电/蒸汽直接计量，非关键工序按容量分摊',
    unit: 'tce/万kVA',
    center: '集控',
    category: '单位产品能耗',
    source: '国家绿色工厂标准',
    scope: '产品型号',
    freq: '月度',
    factory: '沈变本部',
    current: 1.45,
    base: 1.30,
    target: 1.20,
    yoyDiff: 0.15,
    yoyRate: 11.54,
    status: '异常',
    aiReasoning: '本月高压干燥工序蒸汽能耗偏高 18%，主要受 2 号真空干燥罐密封圈老化热损影响。',
  },
  {
    id: 13,
    name: '单位产品电耗',
    definition: '统计期内电能消费量（含公辅）与产品产量的比值',
    formula: 'q电 = Q电 / M',
    desc: '车间电能消耗总量 / 订单合格产品产量',
    unit: 'kWh/万kVA',
    center: '集控',
    category: '单位产品能耗',
    source: '股份管理要求',
    scope: '产品型号',
    freq: '月度',
    factory: '沈变本部',
    current: 10420.0,
    base: 10800.0,
    target: 10000.0,
    yoyDiff: -380.0,
    yoyRate: -3.52,
    status: '正常',
  },
  {
    id: 14,
    name: '单位产品蒸汽消耗',
    definition: '统计期内蒸汽消费量与产品产量的比值',
    formula: 'q蒸汽 = Q蒸汽 / M',
    desc: '干燥及固化工序蒸汽消耗量 / 订单产量',
    unit: 'GJ/万kVA',
    center: '集控',
    category: '单位产品能耗',
    source: '股份管理要求',
    scope: '产品型号',
    freq: '月度',
    factory: '沈变本部',
    current: 4.82,
    base: 4.20,
    target: 4.00,
    yoyDiff: 0.62,
    yoyRate: 14.76,
    status: '异常',
    aiReasoning: '干燥保温周期延长，蒸汽管道排水疏水阀出现微漏。',
  },
  {
    id: 15,
    name: '吨铜电耗（线缆-拉丝）',
    definition: '线缆拉丝工序中每拉1吨铜的耗电量',
    formula: 'q = Q线-拉丝Cu-电 / M线-拉丝Cu',
    desc: '采集铜拉丝机设备电表计量 / 耗铜产量',
    unit: 'kWh/t',
    center: '集控',
    category: '关键工序能耗',
    source: '电装管理要求',
    scope: '线缆产业',
    freq: '月度',
    factory: '鲁缆本部',
    current: 82.4,
    base: 85.0,
    target: 80.0,
    yoyDiff: -2.6,
    yoyRate: -3.06,
    status: '正常',
  },
]

export const periodLabels = ['2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08']

export const indicatorTone = (status: IndicatorStatus) => {
  switch (status) {
    case '优秀':
      return { text: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/30' }
    case '异常':
      return { text: 'text-rose-400', bg: 'bg-rose-500/10', border: 'border-rose-500/30' }
    case '正常':
    default:
      return { text: 'text-sky-400', bg: 'bg-sky-500/10', border: 'border-sky-500/30' }
  }
}

export const indicatorRawData = (ind: Indicator) => [
  { item: '指标名称', value: ind.name, note: '系统唯一元数据标识' },
  { item: '统计周期', value: '2026年8月 (月度)', note: '每月 1 日自动汇总' },
  { item: '当前计算值', value: `${ind.current} ${ind.unit}`, note: '实际核算结果' },
  { item: '集团基准值', value: `${ind.base} ${ind.unit}`, note: '特变电工内部基准' },
  { item: '国家/标杆值', value: `${ind.target} ${ind.unit}`, note: ind.source },
  { item: '数据源头', value: ind.desc, note: '自动采集 + MES/ERP 对接' },
  { item: '核算公式', value: ind.formula, note: '可追溯验证' },
]

export const indicatorTrend = (ind: Indicator) => [
  { period: '1月', 实际值: Number((ind.current * 0.96).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '2月', 实际值: Number((ind.current * 0.94).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '3月', 实际值: Number((ind.current * 1.02).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '4月', 实际值: Number((ind.current * 0.98).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '5月', 实际值: Number((ind.current * 1.05).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '6月', 实际值: Number((ind.current * 1.01).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '7月', 实际值: Number((ind.current * 1.03).toFixed(2)), 基准值: ind.base, 标杆值: ind.target },
  { period: '8月', 实际值: ind.current, 基准值: ind.base, 标杆值: ind.target },
]
