/**
 * 重点用能设备主数据模型与初始数据集 (Key Equipment Data Model & Dataset)
 * 严格对齐特变电工（TBEA）工业设备编码规范与重点用能设备在线监测台账
 */

// 🌟 设备类型选项 (根据特变电工生产设备特性分类)
export const EQUIPMENT_TYPES = [
  '热力与干燥设备',
  '电力试验机组',
  '暖通与空调系统',
  '动力挤压拉丝',
  '空压与动力系统',
  '熔铸冶炼设备',
  '循环水与温控',
  '反应与固化炉群',
  '特种工艺机组',
] as const

export type EquipmentType = typeof EQUIPMENT_TYPES[number]

// 🌟 设备能源消耗类型规范 (严格遵循 8 大能源介质色彩与行业分类)
export interface EnergyMediumMeta {
  key: string
  name: string
  color: string
  bgLight: string
  borderLight: string
  unit: string
}

export const ENERGY_CONSUMPTION_TYPES: EnergyMediumMeta[] = [
  { key: 'elec', name: '电力', color: '#2C7CFF', bgLight: '#eff6ff', borderLight: '#bfdbfe', unit: 'kWh' },
  { key: 'steam', name: '蒸汽', color: '#FFBA00', bgLight: '#fffbeb', borderLight: '#fde68a', unit: 't' },
  { key: 'gas', name: '天然气', color: '#FF6536', bgLight: '#fff7ed', borderLight: '#fed7aa', unit: 'm³' },
  { key: 'nitrogen', name: '液氮', color: '#4F39F6', bgLight: '#f5f3ff', borderLight: '#ddd6fe', unit: 'm³' },
  { key: 'water', name: '水', color: '#10C4CE', bgLight: '#ecfeff', borderLight: '#a5f3fc', unit: 'm³' },
  { key: 'diesel', name: '柴油', color: '#8E73ED', bgLight: '#fbf7ff', borderLight: '#e9d5ff', unit: 'L' },
]

// 🌟 重点用能设备实体定义
export interface KeyEquipmentItem {
  id: string
  code: string // 设备编码, e.g. EQ-SB-DRY-01
  name: string // 设备名称, e.g. 1# 1000kV级气相白真空干燥罐组
  company: string // 2级 经营单位 (沈变公司、衡变公司、新变厂、鲁缆公司、德缆公司、新缆厂)
  enterprise: string // 3级 生产企业/工厂 (沈变本部、露娜公司、衡变本部、新变超高压等)
  workshop: string // 安装位置/车间工段, e.g. 特高压一车间 (真空注油跨)
  deviceType?: string // 设备类型 (可选兼容)
  energyTypes: string[] // 设备能源消耗类型，如 ['电力', '蒸汽']
  spec: string // 规格型号
  ratedPowerKW: number // 额定功率 (kW)
  annualEnergyTce: number // 预估设计年综合能耗 (tce/年)
  status: '启用' | '停用' // 设备状态 (启用 / 停用)
  installDate: string // 投入运行年月 (YYYY-MM)
  manufacturer: string // 制造厂商
  responsiblePerson: string // 责任工程师/维护人
  contactPhone: string // 联系方式
  description?: string // 工艺说明/工况要求
  createdAt?: string
  updatedAt?: string
}

// 🌟 经营单位与生产企业层级联动字典 (严格对齐全系统组织架构树)
export interface CompanyOption {
  company: string
  enterprises: {
    name: string
    code: string
    typicalWorkshops: string[]
  }[]
}

export const ENTERPRISE_HIERARCHY: CompanyOption[] = [
  {
    company: '沈变公司',
    enterprises: [
      { name: '沈变本部', code: 'ws_sb_main', typicalWorkshops: ['特高压一车间 (真空注油跨)', '特高压二车间', '特高压试验大厅', '特高压一车间 (恒温洁净区)'] },
      { name: '露娜公司', code: 'ws_sb_luna', typicalWorkshops: ['智能制造中心', '智能箱变装配区', '机器人激光焊接线'] },
      { name: '和新套管', code: 'ws_sb_hx', typicalWorkshops: ['套管生产车间', '特高压胶浸纸车间', '套管试验站'] },
      { name: '康嘉互感器', code: 'ws_sb_kj', typicalWorkshops: ['互感器总装车间', '光电互感器洁净室', '高压绕线工段'] },
      { name: '智慧能源', code: 'ws_sb_ems', typicalWorkshops: ['智慧能源调度站', '厂区光储充变流站'] },
      { name: '印能公司', code: 'ws_sb_yn', typicalWorkshops: ['绝缘加工车间', '纸板热压工段'] },
    ],
  },
  {
    company: '衡变公司',
    enterprises: [
      { name: '衡变本部', code: 'ws_hb_main', typicalWorkshops: ['干燥辅助站房', '总装一车间', '特高压制造中心 (线圈恒温区)', '储油区油库处理站', '全屏蔽高压试验站', '动力公用工程站房'] },
      { name: '南京公司', code: 'ws_hb_nj', typicalWorkshops: ['电研综测车间', '微机保护试验区'] },
      { name: '云集电气', code: 'ws_hb_yj', typicalWorkshops: ['智能开关一车间', '5G智能成套设备跨'] },
      { name: '湖南电气', code: 'ws_hb_hn', typicalWorkshops: ['智能制造车间', '配网智能化车间'] },
      { name: '云集高压开关', code: 'ws_hb_kg', typicalWorkshops: ['开关总装一车间', '触头数控精密加工跨'] },
      { name: '特缆建', code: 'ws_hb_tnj', typicalWorkshops: ['模块装配跨', '变电舱体总装区'] },
      { name: '合容电气', code: 'ws_hb_hr', typicalWorkshops: ['浸渍固化车间', '高压电容器试验室'] },
      { name: '事杰爱迪', code: 'ws_hb_gil', typicalWorkshops: ['GIL总装一跨', '特高压管道母线装配线'] },
    ],
  },
  {
    company: '新变厂',
    enterprises: [
      { name: '新变本部', code: 'ws_xb_main', typicalWorkshops: ['主变一跨干燥工段', '公用工程动力中心', '750kV主变总装跨'] },
      { name: '超高压公司', code: 'ws_xb_uhv', typicalWorkshops: ['超高压绕线车间', '超高压线圈绕线洁净室'] },
      { name: '天变公司', code: 'ws_xb_tb', typicalWorkshops: ['油箱制造车间', '干变制造车间', '非晶剪切线'] },
      { name: '智能电气', code: 'ws_xb_zndq', typicalWorkshops: ['箱变装配跨', '配变全自动测试线'] },
      { name: '京津冀科技', code: 'ws_xb_jjj', typicalWorkshops: ['浇注净化车间', '真空浇注烘房'] },
      { name: '珠峰硅钢', code: 'ws_xb_zf', typicalWorkshops: ['纵剪一跨', '横剪二跨', '硅钢连续退火线'] },
    ],
  },
  {
    company: '鲁缆公司',
    enterprises: [
      { name: '鲁缆本部', code: 'ws_ll_main', typicalWorkshops: ['超高压立塔车间', '绞线一车间', '超高压立塔车间 (塔顶洁净机房)', '立塔交联二跨', '铜材熔铸加工分厂', '铝包覆加工工段'] },
      { name: '曙光公司', code: 'ws_ll_sg', typicalWorkshops: ['橡缆挤塑车间', '挤塑二跨', '特种阻燃辐照区'] },
      { name: '特种电缆厂', code: 'ws_ll_tz', typicalWorkshops: ['特缆辐照加工防护区', '光电复合缆车间'] },
    ],
  },
  {
    company: '新缆厂',
    enterprises: [
      { name: '新缆本部', code: 'ws_xl_main', typicalWorkshops: ['挤塑一跨', '铝加工冶炼跨', '架空绝缘导线二跨'] },
      { name: '特变电工新疆电缆有限公司', code: 'ws_xl_dl', typicalWorkshops: ['交联车间', '拉丝车间', '高压挤塑二跨'] },
      { name: '特变电工新疆线缆厂', code: 'ws_xl_xl', typicalWorkshops: ['绞线二跨', '特种线缆制造部'] },
    ],
  },
  {
    company: '德缆公司',
    enterprises: [
      { name: '德缆本部', code: 'ws_dl_main', typicalWorkshops: ['矿用橡套电缆车间', '热处理二车间', '重型挤塑跨'] },
      { name: '特变电工（德阳）电缆股份有限公司', code: 'ws_dl_dy', typicalWorkshops: ['连铸连轧车间', '特种挤塑车间', '高压扁线车间'] },
      { name: '布电线车间', code: 'ws_dl_bdx', typicalWorkshops: ['拉丝拔丝跨', '全自动双绞线区'] },
    ],
  },
]

// 🌟 全集团重点用能设备初始数据集 (严格对齐重点用能设备在线监测台账)
export const INITIAL_KEY_EQUIPMENT_LIST: KeyEquipmentItem[] = [
  // -------------------------------------------------------------
  // 1. 沈变公司
  // -------------------------------------------------------------
  {
    id: 'eq-001',
    code: 'EQ-SB-DRY-01',
    name: '1# 1000kV级气相白真空干燥罐组',
    company: '沈变公司',
    enterprise: '沈变本部',
    workshop: '特高压一车间 (真空注油跨)',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'VF-1000/120',
    ratedPowerKW: 4680,
    annualEnergyTce: 3240,
    status: '启用',
    installDate: '2021-04',
    manufacturer: '德国利波尔 (Hedrich) / 特变装备联合研制',
    responsiblePerson: '张立国',
    contactPhone: '138-4011-8892',
    description: '特高压交流变压器器身绝缘处理核心设备，气相煤油循环加热脱水，主消耗高压过热蒸汽与电加热真空泵组。',
  },
  {
    id: 'eq-002',
    code: 'EQ-SB-DRY-02',
    name: '2# 特高压变压器煤油汽相干燥罐',
    company: '沈变公司',
    enterprise: '沈变本部',
    workshop: '特高压二车间',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'VF-800/100',
    ratedPowerKW: 3950,
    annualEnergyTce: 2850,
    status: '启用',
    installDate: '2022-08',
    manufacturer: '特变电工沈阳装备制造有限公司',
    responsiblePerson: '刘海鹏',
    contactPhone: '139-4022-3341',
    description: '±800kV换流变与骨干主变绝缘深度脱水，蒸汽热媒间接冷凝置换，配备大流量水环真空泵组。',
  },
  {
    id: 'eq-003',
    code: 'EQ-SB-TST-01',
    name: '1# 1000kV特高压工频耐压试验机组',
    company: '沈变公司',
    enterprise: '沈变本部',
    workshop: '特高压试验大厅',
    deviceType: '电力试验机组',
    energyTypes: ['电力'],
    spec: 'TS-3000MVA/1200kV',
    ratedPowerKW: 2850,
    annualEnergyTce: 1820,
    status: '启用',
    installDate: '2020-11',
    manufacturer: '特变电工特高压电气技术中心',
    responsiblePerson: '王振宇',
    contactPhone: '137-0401-7765',
    description: '特高压变压器短路耐受、雷电冲击与局部放电综合测试机组，短时脉冲冲击功率极高，严格需量管控。',
  },
  {
    id: 'eq-sb-ac-01',
    code: 'EQ-SB-AC-01',
    name: '1# 洁净装配跨恒温恒湿精密空调机组',
    company: '沈变公司',
    enterprise: '沈变本部',
    workshop: '特高压一车间 (恒温洁净区)',
    deviceType: '暖通与空调系统',
    energyTypes: ['电力'],
    spec: 'YORK-YK-850TR',
    ratedPowerKW: 820,
    annualEnergyTce: 480,
    status: '启用',
    installDate: '2022-05',
    manufacturer: '约克 (York) / 约克广州空调冷冻设备有限公司',
    responsiblePerson: '高德胜',
    contactPhone: '138-4015-6677',
    description: '特高压特大容量变压器总装洁净跨恒温恒湿空调机组，采用全变频离心式冷水机组与精密温湿度控制末端，严格维持车间环境20±2℃、相对湿度≤45%。仅消耗纯电力动力能耗。',
  },
  {
    id: 'eq-004',
    code: 'EQ-LN-CRYO-01',
    name: '1# 液氮深冷装配与惰化循环机组',
    company: '沈变公司',
    enterprise: '露娜公司',
    workshop: '智能制造中心',
    deviceType: '特种工艺机组',
    energyTypes: ['电力', '水'],
    spec: 'LN-CRYO-500',
    ratedPowerKW: 1420,
    annualEnergyTce: 890,
    status: '启用',
    installDate: '2023-05',
    manufacturer: '特变电工智能电气技术装备分公司',
    responsiblePerson: '赵恒志',
    contactPhone: '136-1402-9988',
    description: '智能配网箱变超高真空注油密封系统，配合液氮深冷真空捕集冷阱，消耗循环冷却水与动力电力。',
  },
  {
    id: 'eq-sb-ems-01',
    code: 'EQ-SB-EMS-01',
    name: '1# 厂区光储充微电网并网变流机组',
    company: '沈变公司',
    enterprise: '智慧能源',
    workshop: '智慧能源调度站',
    deviceType: '电力试验机组',
    energyTypes: ['电力'],
    spec: 'PCS-1500kW/1500V',
    ratedPowerKW: 1650,
    annualEnergyTce: 750,
    status: '启用',
    installDate: '2022-09',
    manufacturer: '特变电工新能源股份有限公司',
    responsiblePerson: '郭海波',
    contactPhone: '138-4033-1122',
    description: '园区分布式光储充一体化集中并网PCS变流站，负责削峰填谷与微电网无缝并离网切变。',
  },
  {
    id: 'eq-005',
    code: 'EQ-HX-FURN-01',
    name: '1# 800kV特高压干式电容套管固化炉',
    company: '沈变公司',
    enterprise: '和新套管',
    workshop: '套管生产车间',
    deviceType: '反应与固化炉群',
    energyTypes: ['电力', '蒸汽'],
    spec: 'HX-OVEN-1100',
    ratedPowerKW: 1850,
    annualEnergyTce: 1650,
    status: '启用',
    installDate: '2022-03',
    manufacturer: '西安电炉研究所 / 和新套管联合定制',
    responsiblePerson: '孙维民',
    contactPhone: '135-2401-6622',
    description: '特高压特大口径套管芯体阶梯温控固化烘炉，双能源互补（电预热+蒸汽热风循环保温）。',
  },
  {
    id: 'eq-006',
    code: 'EQ-KJ-VAC-01',
    name: '1# 500kV互感器绝缘注油真空机组',
    company: '沈变公司',
    enterprise: '康嘉互感器',
    workshop: '互感器总装车间',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'KJ-CAST-1000',
    ratedPowerKW: 1120,
    annualEnergyTce: 720,
    status: '启用',
    installDate: '2023-09',
    manufacturer: '瑞士喜利得 (Hedrich Casting)',
    responsiblePerson: '马文祥',
    contactPhone: '139-4088-1123',
    description: '特高压电子式互感器高精度配料脱气浇注线，恒温夹套消耗循环变频动力电。',
  },
  {
    id: 'eq-yn-prs-01',
    code: 'EQ-YN-PRS-01',
    name: '1# 变压器绝缘纸板热压整形生产线',
    company: '沈变公司',
    enterprise: '印能公司',
    workshop: '绝缘加工车间',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'YN-PRESS-1600',
    ratedPowerKW: 980,
    annualEnergyTce: 650,
    status: '启用',
    installDate: '2021-12',
    manufacturer: '沈阳重工装备制造有限公司',
    responsiblePerson: '宋文斌',
    contactPhone: '136-4022-9911',
    description: '变压器超高密度绝缘成型件液压热压成型机组，饱和高温蒸汽加热板配动力液压泵。',
  },

  // -------------------------------------------------------------
  // 2. 衡变公司
  // -------------------------------------------------------------
  {
    id: 'eq-hb-rec-01',
    code: 'EQ-HB-REC-01',
    name: '6# 煤油喷淋回收及热循环系统',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '干燥辅助站房',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'HB-REC-2000',
    ratedPowerKW: 1050,
    annualEnergyTce: 780,
    status: '启用',
    installDate: '2020-07',
    manufacturer: '特变电工衡阳变压器有限公司',
    responsiblePerson: '周伟刚',
    contactPhone: '137-7342-8811',
    description: '煤油气相干燥热循环回收系统，冷凝换热消耗高压蒸汽与全变频动力机泵。',
  },
  {
    id: 'eq-007',
    code: 'EQ-HB-MAIN-01',
    name: '1# 750kV大型发电机主变压罐装线',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '总装一车间',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'HB-VF-1200',
    ratedPowerKW: 3600,
    annualEnergyTce: 2600,
    status: '启用',
    installDate: '2021-10',
    manufacturer: '特变电工衡阳变压器有限公司',
    responsiblePerson: '陈志强',
    contactPhone: '138-7341-9922',
    description: '华南最大容量特高压变压器汽相干燥处理罐，消耗工业园区集中直供高压蒸汽。',
  },
  {
    id: 'eq-hb-ac-01',
    code: 'EQ-HB-AC-01',
    name: '1# 特高压线圈车间集中中央空调机组',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '特高压制造中心 (线圈恒温区)',
    deviceType: '暖通与空调系统',
    energyTypes: ['电力'],
    spec: 'TRANE-RTWD-750',
    ratedPowerKW: 750,
    annualEnergyTce: 430,
    status: '启用',
    installDate: '2021-08',
    manufacturer: '特灵空调 (Trane) 系统集成有限公司',
    responsiblePerson: '蒋建辉',
    contactPhone: '137-7346-5588',
    description: '衡变特高压主变绕线车间高精度温控中央空调机组，变频水冷螺杆配双回路节能循环泵，保持超高压绝缘线圈绕制无尘恒温工况。仅消耗纯电力。',
  },
  {
    id: 'eq-008',
    code: 'EQ-HB-REC-02',
    name: '大型热油真空净化与再生机组',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '储油区油库处理站',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'ZY-30000L/h',
    ratedPowerKW: 1450,
    annualEnergyTce: 640,
    status: '启用',
    installDate: '2020-07',
    manufacturer: '重庆聚联绝缘油技术公司',
    responsiblePerson: '李志刚',
    contactPhone: '137-7342-8812',
    description: '主变绝缘油大容量微水、微气与杂质多级脱除系统，全电磁感应高效加热。',
  },
  {
    id: 'eq-009',
    code: 'EQ-HB-TST-01',
    name: '1200kV特高压冲击电压发生器试验套件',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '全屏蔽高压试验站',
    deviceType: '电力试验机组',
    energyTypes: ['电力'],
    spec: 'IVG-7200kJ/1200kV',
    ratedPowerKW: 4100,
    annualEnergyTce: 1250,
    status: '启用',
    installDate: '2022-01',
    manufacturer: '特变电工特高压试验站',
    responsiblePerson: '何建国',
    contactPhone: '139-7340-5566',
    description: '变压器全波与截波雷电冲击绝缘耐压核验系统，高电压毫秒级充放电控制。',
  },
  {
    id: 'eq-010',
    code: 'EQ-HB-PUMP-01',
    name: '衡变全厂智慧动力循环供水泵站',
    company: '衡变公司',
    enterprise: '衡变本部',
    workshop: '动力公用工程站房',
    deviceType: '循环水与温控',
    energyTypes: ['电力', '水'],
    spec: 'PUMP-2500m³/h-45m',
    ratedPowerKW: 1280,
    annualEnergyTce: 980,
    status: '启用',
    installDate: '2021-03',
    manufacturer: '上海凯泉泵业 / 特变电工联合集成',
    responsiblePerson: '郭少杰',
    contactPhone: '136-7345-1234',
    description: '特大跨度厂房冷却循环水与消防稳压综合水力枢纽，全变频恒压调控。',
  },
  {
    id: 'eq-nj-test-01',
    code: 'EQ-NJ-TEST-01',
    name: '1# 继电保护与智能控制综测平台',
    company: '衡变公司',
    enterprise: '南京公司',
    workshop: '电研综测车间',
    deviceType: '电力试验机组',
    energyTypes: ['电力'],
    spec: 'NJ-TEST-500',
    ratedPowerKW: 680,
    annualEnergyTce: 380,
    status: '启用',
    installDate: '2023-04',
    manufacturer: '特变电工南京智能电气有限公司',
    responsiblePerson: '陈明远',
    contactPhone: '138-2501-7788',
    description: '数字化继电保护装置批量带电老化与全工况模拟综测台，高精度受电。',
  },
  {
    id: 'eq-yj-gis-01',
    code: 'EQ-YJ-GIS-01',
    name: '1# 220kV GIS断路器自动化装配检测线',
    company: '衡变公司',
    enterprise: '云集电气',
    workshop: '智能开关一车间',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'YJ-GIS-220',
    ratedPowerKW: 920,
    annualEnergyTce: 510,
    status: '启用',
    installDate: '2022-11',
    manufacturer: '特变电工云集电气有限公司',
    responsiblePerson: '邓建军',
    contactPhone: '139-7345-6677',
    description: '高压气体绝缘开关六氟化硫自动抽真空与氦质谱检漏装配流水线。',
  },
  {
    id: 'eq-hn-robot-01',
    code: 'EQ-HN-ROBOT-01',
    name: '1# 220kV箱变自动焊接机器人工作站',
    company: '衡变公司',
    enterprise: '湖南电气',
    workshop: '智能制造车间',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'HN-ROBOT-220',
    ratedPowerKW: 780,
    annualEnergyTce: 420,
    status: '启用',
    installDate: '2023-06',
    manufacturer: '安川电机 (Yaskawa) / 特变电工集成',
    responsiblePerson: '罗文斌',
    contactPhone: '136-7341-2233',
    description: '预制式智能变电站箱体大型龙门六轴双机协同激光跟踪自动焊接工作站。',
  },
  {
    id: 'eq-yj-sw-01',
    code: 'EQ-YJ-SW-01',
    name: '1# 500kV隔离开关触头精密加工机组',
    company: '衡变公司',
    enterprise: '云集高压开关',
    workshop: '开关总装一车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'YJ-CNC-500',
    ratedPowerKW: 640,
    annualEnergyTce: 360,
    status: '启用',
    installDate: '2022-04',
    manufacturer: '沈阳机床五轴加工中心',
    responsiblePerson: '彭志强',
    contactPhone: '138-7348-9900',
    description: '特高压GW系列高导电耐磨触头多轴联动数控铣削与银层钝化成型机组。',
  },
  {
    id: 'eq-tnj-eng-01',
    code: 'EQ-TNJ-ENG-01',
    name: '1# 输变电工程模块化预制舱组装工位',
    company: '衡变公司',
    enterprise: '特缆建',
    workshop: '模块装配跨',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'TNJ-MOD-100',
    ratedPowerKW: 580,
    annualEnergyTce: 320,
    status: '启用',
    installDate: '2023-01',
    manufacturer: '特能建装配工程装备部',
    responsiblePerson: '胡锦荣',
    contactPhone: '137-7349-4455',
    description: '新能源大基地升压站预装式模块化电舱整体起吊、管线穿隔与气密测试线。',
  },
  {
    id: 'eq-hr-cap-01',
    code: 'EQ-HR-CAP-01',
    name: '1# 500kV高压并联电容器真空浸渍罐',
    company: '衡变公司',
    enterprise: '合容电气',
    workshop: '浸渍固化车间',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'HR-VAC-500',
    ratedPowerKW: 860,
    annualEnergyTce: 490,
    status: '启用',
    installDate: '2022-09',
    manufacturer: '特变电工合容电气有限公司',
    responsiblePerson: '杜文斌',
    contactPhone: '135-7340-1122',
    description: '大容量电力补偿电容器芯子高真空绝缘油恒温脱水与压力浸渍处理罐。',
  },
  {
    id: 'eq-gil-asm-01',
    code: 'EQ-GIL-ASM-01',
    name: '1# 1100kV特高压GIL气体绝缘输电线路装配线',
    company: '衡变公司',
    enterprise: '事杰爱迪',
    workshop: 'GIL总装一跨',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'GIL-1100kV-LINE',
    ratedPowerKW: 1350,
    annualEnergyTce: 750,
    status: '启用',
    installDate: '2023-08',
    manufacturer: '事杰爱迪特高压电气装备制造部',
    responsiblePerson: '向国庆',
    contactPhone: '139-7341-3344',
    description: '特高压三相共箱及单相GIL管道导体微粒清洁、对接焊与高真空充气密封线。',
  },

  // -------------------------------------------------------------
  // 3. 新变厂
  // -------------------------------------------------------------
  {
    id: 'eq-xb-wind-01',
    code: 'EQ-XB-WIND-01',
    name: '1# 750kV级超高压线圈立式绕线机',
    company: '新变厂',
    enterprise: '超高压公司',
    workshop: '超高压绕线车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'XB-WIND-750',
    ratedPowerKW: 1280,
    annualEnergyTce: 760,
    status: '启用',
    installDate: '2021-06',
    manufacturer: '瑞士杜堡 (Tuboly-Astronic)',
    responsiblePerson: '阿布力米提',
    contactPhone: '138-9985-7766',
    description: '大型特高压主变线圈全自动张力恒定立式数控绕线机组，多伺服电机联控。',
  },
  {
    id: 'eq-xb-ac-01',
    code: 'EQ-XB-AC-01',
    name: '1# 超高压绝缘洁净跨变频精密空调机组',
    company: '新变厂',
    enterprise: '超高压公司',
    workshop: '超高压线圈绕线洁净室',
    deviceType: '暖通与空调系统',
    energyTypes: ['电力'],
    spec: 'MIDEA-V8-680',
    ratedPowerKW: 680,
    annualEnergyTce: 390,
    status: '启用',
    installDate: '2023-03',
    manufacturer: '美的暖通与楼宇工业设备公司',
    responsiblePerson: '买买提江',
    contactPhone: '139-9988-2233',
    description: '西北干旱温差工况专用全变频精密风冷直膨式空调系统，带双级初中高效空气净化与恒温恒湿除湿段。仅消耗电力动力。',
  },
  {
    id: 'eq-012',
    code: 'EQ-XB-MAIN-01',
    name: '新变 750kV 煤油气相真空干燥罐系统',
    company: '新变厂',
    enterprise: '新变本部',
    workshop: '主变一跨干燥工段',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'XB-VF-750',
    ratedPowerKW: 3820,
    annualEnergyTce: 2650,
    status: '启用',
    installDate: '2020-05',
    manufacturer: '特变电工装备制造中心',
    responsiblePerson: '阿不都热西提',
    contactPhone: '138-9981-6622',
    description: '服务西北电网特大容量750kV主变干燥脱水，蒸汽与电热双工质协同。',
  },
  {
    id: 'eq-013',
    code: 'EQ-XB-AIR-01',
    name: '西北工业园区无油螺杆空压机联控群',
    company: '新变厂',
    enterprise: '新变本部',
    workshop: '公用工程动力中心',
    deviceType: '空压与动力系统',
    energyTypes: ['电力'],
    spec: 'AC-ZR350-VSD*4',
    ratedPowerKW: 1400,
    annualEnergyTce: 1120,
    status: '启用',
    installDate: '2022-06',
    manufacturer: '阿特拉斯·科普柯 (Atlas Copco)',
    responsiblePerson: '李向东',
    contactPhone: '139-9985-3344',
    description: '四机联控无油级压缩空气气源站，变频精准匹配全厂气动工具与注油气动阀门。',
  },
  {
    id: 'eq-tb-tank-01',
    code: 'EQ-TB-TANK-01',
    name: '1# 牵引变压器波纹油箱成型机组',
    company: '新变厂',
    enterprise: '天变公司',
    workshop: '油箱制造车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '水'],
    spec: 'TB-TANK-400',
    ratedPowerKW: 1650,
    annualEnergyTce: 950,
    status: '启用',
    installDate: '2021-09',
    manufacturer: '天变装备自动化分厂',
    responsiblePerson: '赵志军',
    contactPhone: '136-9985-1122',
    description: '高速铁路牵引变压器超薄波纹散热油箱全自动滚轧冷弯与水压胀型机组。',
  },
  {
    id: 'eq-014',
    code: 'EQ-XB-CAST-01',
    name: '干式变压器微电脑环氧真空静态浇注站',
    company: '新变厂',
    enterprise: '天变公司',
    workshop: '干变制造车间',
    deviceType: '反应与固化炉群',
    energyTypes: ['电力'],
    spec: 'TB-VDC-400',
    ratedPowerKW: 1250,
    annualEnergyTce: 580,
    status: '启用',
    installDate: '2023-04',
    manufacturer: '德国霍伯斯 (Hubers)',
    responsiblePerson: '杨建华',
    contactPhone: '136-9982-1100',
    description: '环氧树脂高真空静态薄膜脱气浇注线，高精度温度区控加热板。',
  },
  {
    id: 'eq-xb-box-01',
    code: 'EQ-XB-BOX-01',
    name: '1# 110kV智能箱式变电站装配检测线',
    company: '新变厂',
    enterprise: '智能电气',
    workshop: '箱变装配跨',
    deviceType: '特种工艺机组',
    energyTypes: ['电力'],
    spec: 'XB-ZNDQ-110',
    ratedPowerKW: 890,
    annualEnergyTce: 510,
    status: '启用',
    installDate: '2022-10',
    manufacturer: '特变电工智能电气配电装备厂',
    responsiblePerson: '王海滨',
    contactPhone: '138-9987-4433',
    description: '新能源电站箱式变电站壳体流水线自动组装、一次母线安装与出厂自动化试验台。',
  },
  {
    id: 'eq-xb-cast-01',
    code: 'EQ-XB-CAST-02',
    name: '1# 110kV环氧树脂真空浇注罐',
    company: '新变厂',
    enterprise: '京津冀科技',
    workshop: '浇注净化车间',
    deviceType: '反应与固化炉群',
    energyTypes: ['电力'],
    spec: 'JJJ-CAST-110',
    ratedPowerKW: 1180,
    annualEnergyTce: 660,
    status: '启用',
    installDate: '2023-02',
    manufacturer: '特变电工京津冀智能装备中心',
    responsiblePerson: '张建民',
    contactPhone: '137-9982-5566',
    description: '干式环氧绝缘线圈配料自动混料机及阶梯梯度程序加温固化罐。',
  },
  {
    id: 'eq-xb-shr-01',
    code: 'EQ-XB-SHR-01',
    name: '5# 铁心纵剪硅钢片十头纵剪线',
    company: '新变厂',
    enterprise: '珠峰硅钢',
    workshop: '纵剪一跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'ZF-SHR-1000',
    ratedPowerKW: 960,
    annualEnergyTce: 540,
    status: '启用',
    installDate: '2021-08',
    manufacturer: '日本丸嘉 (Maruka)',
    responsiblePerson: '刘志鹏',
    contactPhone: '139-9986-7788',
    description: '高导磁高磁感取向硅钢母卷超高速纵剪分条开卷线，微米级毛刺控制。',
  },
  {
    id: 'eq-zf-cut-01',
    code: 'EQ-ZF-CUT-01',
    name: '1# 高导磁取向硅钢连续横剪线',
    company: '新变厂',
    enterprise: '珠峰硅钢',
    workshop: '横剪二跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'ZF-CUT-800',
    ratedPowerKW: 840,
    annualEnergyTce: 480,
    status: '启用',
    installDate: '2022-03',
    manufacturer: '德国乔格 (Heinrich Georg)',
    responsiblePerson: '马龙',
    contactPhone: '136-9981-3322',
    description: '变压器大型阶梯搭接斜接缝铁心片伺服定长精密数控横剪剪切线。',
  },

  // -------------------------------------------------------------
  // 4. 鲁缆公司
  // -------------------------------------------------------------
  {
    id: 'eq-dry-03',
    code: 'EQ-LL-VCV-01',
    name: '3# 500kV 悬垂立塔交联生产线',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '超高压立塔车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '蒸汽'],
    spec: 'MAIL-VCV-500',
    ratedPowerKW: 3850,
    annualEnergyTce: 3200,
    status: '启用',
    installDate: '2021-08',
    manufacturer: '芬兰麦拉菲尔 (Maillefer)',
    responsiblePerson: '张树敏',
    contactPhone: '138-5381-8899',
    description: '电缆产业高能耗标志性机组，156米立塔重力下沉挤塑，高温饱和高压蒸汽交联管。',
  },
  {
    id: 'eq-ll-str-01',
    code: 'EQ-LL-STR-01',
    name: '1# 35kV铝合金绞线机组',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '绞线一车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'LL-STR-630',
    ratedPowerKW: 1150,
    annualEnergyTce: 680,
    status: '启用',
    installDate: '2022-04',
    manufacturer: '无锡恒新电缆机械有限公司',
    responsiblePerson: '陈培华',
    contactPhone: '139-5386-3322',
    description: '大截面耐热铝合金绞线机组，多盘恒张力伺服退扭框式绞线机群。',
  },
  {
    id: 'eq-ll-ac-01',
    code: 'EQ-LL-AC-01',
    name: '1# 超高压立塔交联机房恒温空调机组',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '超高压立塔车间 (塔顶洁净机房)',
    deviceType: '暖通与空调系统',
    energyTypes: ['电力'],
    spec: 'DAIKIN-VRV-520',
    ratedPowerKW: 520,
    annualEnergyTce: 310,
    status: '启用',
    installDate: '2022-10',
    manufacturer: '大金空调工业 (中国) 有限公司',
    responsiblePerson: '张立峰',
    contactPhone: '136-5389-1100',
    description: '156米立塔高位交联上料与控制机房专用恒温空调机组，应对立塔高空风阻与温差，确保精密挤塑测径传感器稳定工作。仅消耗电力。',
  },
  {
    id: 'eq-016',
    code: 'EQ-LL-VCV-02',
    name: '2# 220kV高压立塔交联聚乙烯电缆机组',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '立塔交联二跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '液氮', '水'],
    spec: 'MAIL-VCV-220',
    ratedPowerKW: 3680,
    annualEnergyTce: 2950,
    status: '启用',
    installDate: '2022-11',
    manufacturer: '芬兰麦拉菲尔 (Maillefer)',
    responsiblePerson: '鲁培华',
    contactPhone: '139-5382-7766',
    description: '220kV及以下高压电缆连续交联生产线，纯液氮封闭保压防氧化交联。',
  },
  {
    id: 'eq-017',
    code: 'EQ-LL-MELT-01',
    name: '30吨/小时节能型双立炉铜连铸连轧机组',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '铜材熔铸加工分厂',
    deviceType: '熔铸冶炼设备',
    energyTypes: ['天然气', '电力', '水'],
    spec: 'SCR-30T-CCR',
    ratedPowerKW: 6800,
    annualEnergyTce: 5800,
    status: '启用',
    installDate: '2020-03',
    manufacturer: '美国南线 (Southwire) / 鲁缆定制',
    responsiblePerson: '曹广志',
    contactPhone: '137-5383-4411',
    description: '全厂最大天然气实物量消耗机组，高纯阴极铜连续竖炉熔化、保温炉转注与粗轧拉丝。',
  },
  {
    id: 'eq-018',
    code: 'EQ-LL-EXT-01',
    name: '连续挤压无缝铝护套成型机组',
    company: '鲁缆公司',
    enterprise: '鲁缆本部',
    workshop: '铝包覆加工工段',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'CONFORM-LJ500',
    ratedPowerKW: 2850,
    annualEnergyTce: 1820,
    status: '启用',
    installDate: '2021-12',
    manufacturer: '大连铁道研究所 / 康福姆 (Conform)',
    responsiblePerson: '徐金生',
    contactPhone: '136-5380-9922',
    description: '高压电缆金属皱纹铝护套连续摩擦热挤压线，大扭矩大功率主驱电机。',
  },
  {
    id: 'eq-dry-04',
    code: 'EQ-SG-CV-01',
    name: '4# 连续硫化橡胶挤塑机组',
    company: '鲁缆公司',
    enterprise: '曙光公司',
    workshop: '橡缆挤塑车间',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'SG-CV-60',
    ratedPowerKW: 1620,
    annualEnergyTce: 1280,
    status: '启用',
    installDate: '2021-05',
    manufacturer: '特变电工曙光装备车间',
    responsiblePerson: '郭海',
    contactPhone: '138-5387-5544',
    description: '特种船用及矿用橡套电缆连硫挤塑生产线，高温饱和高压蒸汽硫化管。',
  },
  {
    id: 'eq-sg-ext-01',
    code: 'EQ-SG-EXT-01',
    name: '1# 船用特种防火阻燃挤出机组',
    company: '鲁缆公司',
    enterprise: '曙光公司',
    workshop: '挤塑二跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '水'],
    spec: 'SG-EXT-90',
    ratedPowerKW: 980,
    annualEnergyTce: 580,
    status: '启用',
    installDate: '2022-08',
    manufacturer: '南京橡塑机械厂',
    responsiblePerson: '李志刚',
    contactPhone: '137-5382-1199',
    description: '低烟无卤高阻燃环保型船用电缆护套共挤机组，高扭矩螺杆与循环水冷却槽。',
  },
  {
    id: 'eq-019',
    code: 'EQ-LL-IRR-01',
    name: '高能电子加速器辐射交联生产线',
    company: '鲁缆公司',
    enterprise: '特种电缆厂',
    workshop: '特缆辐照加工防护区',
    deviceType: '特种工艺机组',
    energyTypes: ['电力', '水'],
    spec: 'EA-2.5MeV/80mA',
    ratedPowerKW: 1950,
    annualEnergyTce: 940,
    status: '启用',
    installDate: '2023-01',
    manufacturer: '中国科学院近代物理所 / 中广核达胜',
    responsiblePerson: '魏晓峰',
    contactPhone: '135-5385-6677',
    description: '环保光伏电线与新能源汽车高压线电子束交联系统，闭式高纯水冷却水循环。',
  },

  // -------------------------------------------------------------
  // 5. 新缆厂
  // -------------------------------------------------------------
  {
    id: 'eq-dry-07',
    code: 'EQ-XL-VCV-01',
    name: '7# 35kV及以下三层共挤交联生产线',
    company: '新缆厂',
    enterprise: '特变电工新疆电缆有限公司',
    workshop: '交联车间',
    deviceType: '热力与干燥设备',
    energyTypes: ['电力', '蒸汽'],
    spec: 'XL-CCV-35',
    ratedPowerKW: 2450,
    annualEnergyTce: 1980,
    status: '启用',
    installDate: '2021-03',
    manufacturer: '特变电工新疆线缆总厂',
    responsiblePerson: '买买提明',
    contactPhone: '138-9912-7788',
    description: '悬链式三层共挤干法化学交联生产线，蒸汽预热与循环冷水段结合。',
  },
  {
    id: 'eq-xl-draw-01',
    code: 'EQ-XL-DRAW-01',
    name: '1# 大拉连续退火铜大拉机组',
    company: '新缆厂',
    enterprise: '特变电工新疆电缆有限公司',
    workshop: '拉丝车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '水'],
    spec: 'XL-DRAW-450',
    ratedPowerKW: 1820,
    annualEnergyTce: 1100,
    status: '启用',
    installDate: '2022-07',
    manufacturer: '无锡恒新机械有限公司',
    responsiblePerson: '艾力江',
    contactPhone: '139-9914-5566',
    description: '无氧铜杆高速9模滑动式拉丝与直流接触电阻连续退火机，大功率水泵循环喷淋。',
  },
  {
    id: 'eq-xl-str-01',
    code: 'EQ-XL-STR-01',
    name: '1# 铝合金架空导线高速框绞机组',
    company: '新缆厂',
    enterprise: '特变电工新疆线缆厂',
    workshop: '绞线二跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'XL-STR-500',
    ratedPowerKW: 1360,
    annualEnergyTce: 820,
    status: '启用',
    installDate: '2021-11',
    manufacturer: '特变电工新疆装备分公司',
    responsiblePerson: '张永强',
    contactPhone: '139-9915-4422',
    description: '特高压交流输变电工程大截面钢芯铝绞线与耐热铝合金绞线框式绞制线。',
  },
  {
    id: 'eq-023',
    code: 'EQ-XL-EXT-01',
    name: '大口径塑料绝缘电力电缆挤塑机组',
    company: '新缆厂',
    enterprise: '新缆本部',
    workshop: '挤塑一跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'SJ-150/25D',
    ratedPowerKW: 1850,
    annualEnergyTce: 1150,
    status: '启用',
    installDate: '2021-04',
    manufacturer: '特变电工新缆装备分公司',
    responsiblePerson: '买买提明',
    contactPhone: '138-9912-7788',
    description: '35kV及以下交联与聚氯乙烯绝缘外护套挤塑成型，机筒加热器阵列控温。',
  },
  {
    id: 'eq-024',
    code: 'EQ-XL-FURN-01',
    name: '新缆铝杆连铸连轧天然气保温炉机组',
    company: '新缆厂',
    enterprise: '新缆本部',
    workshop: '铝加工冶炼跨',
    deviceType: '熔铸冶炼设备',
    energyTypes: ['天然气', '电力'],
    spec: 'AL-MELT-15T',
    ratedPowerKW: 2600,
    annualEnergyTce: 2980,
    status: '启用',
    installDate: '2022-03',
    manufacturer: '洛阳耐火热工设计院',
    responsiblePerson: '张永强',
    contactPhone: '139-9915-4422',
    description: '电工圆铝杆熔炼与电磁搅拌保温炉群，兼有天然气燃烧与电磁感应系统。',
  },

  // -------------------------------------------------------------
  // 6. 德缆公司
  // -------------------------------------------------------------
  {
    id: 'eq-dry-08',
    code: 'EQ-DL-AL-01',
    name: '8# 铝合金杆连铸连轧机组',
    company: '德缆公司',
    enterprise: '特变电工（德阳）电缆股份有限公司',
    workshop: '连铸连轧车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '水'],
    spec: 'DL-CCR-1800',
    ratedPowerKW: 2950,
    annualEnergyTce: 2150,
    status: '启用',
    installDate: '2021-08',
    manufacturer: '特变电工德缆装备中心',
    responsiblePerson: '刘志刚',
    contactPhone: '138-8105-3344',
    description: '稀土高铁铝合金杆材连续水平结晶浇铸与无间隙冷轧生产线。',
  },
  {
    id: 'eq-dl-ext-01',
    code: 'EQ-DL-EXT-01',
    name: '1# 轨道交通特种扁线挤压包覆机',
    company: '德缆公司',
    enterprise: '特变电工（德阳）电缆股份有限公司',
    workshop: '特种挤塑车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力'],
    spec: 'DL-FLAT-120',
    ratedPowerKW: 1480,
    annualEnergyTce: 890,
    status: '启用',
    installDate: '2022-06',
    manufacturer: '德国尼霍夫 (NIEHOFF)',
    responsiblePerson: '吴建强',
    contactPhone: '139-8102-7788',
    description: '高铁动车牵引电机高绝缘特种薄壁绕组扁线挤出机组，高精度温度闭环。',
  },
  {
    id: 'eq-020',
    code: 'EQ-DL-RUB-01',
    name: '重型橡套电缆连续硫化挤出生产线 (CVLine)',
    company: '德缆公司',
    enterprise: '德缆本部',
    workshop: '矿用橡套电缆车间',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '蒸汽'],
    spec: 'TROEST-CV-80',
    ratedPowerKW: 3100,
    annualEnergyTce: 2450,
    status: '启用',
    installDate: '2021-05',
    manufacturer: '德国特罗斯特 (Troester GmbH)',
    responsiblePerson: '曾令海',
    contactPhone: '138-8101-3322',
    description: '矿用与风电扭缆特种橡胶护套连续高温高压蒸汽硫化生产线。',
  },
  {
    id: 'eq-021',
    code: 'EQ-DL-DRAW-01',
    name: '双头全自动微电脑高速大拉丝退火机组',
    company: '德缆公司',
    enterprise: '布电线车间',
    workshop: '拉丝拔丝跨',
    deviceType: '动力挤压拉丝',
    energyTypes: ['电力', '水'],
    spec: 'NIEHOFF-MSM-85',
    ratedPowerKW: 2200,
    annualEnergyTce: 1350,
    status: '启用',
    installDate: '2022-09',
    manufacturer: '德国尼霍夫 (Maschinenfabrik NIEHOFF)',
    responsiblePerson: '罗兴武',
    contactPhone: '139-8105-8844',
    description: '铜杆高速精密拉细与直流连续接触式电阻退火机组，润滑液大流量循环水冷却。',
  },
  {
    id: 'eq-022',
    code: 'EQ-DL-GAS-01',
    name: '德缆大型天然气铜杆热风退火炉',
    company: '德缆公司',
    enterprise: '德缆本部',
    workshop: '热处理二车间',
    deviceType: '熔铸冶炼设备',
    energyTypes: ['天然气', '电力'],
    spec: 'DL-ANNEAL-20T',
    ratedPowerKW: 1680,
    annualEnergyTce: 1890,
    status: '启用',
    installDate: '2020-08',
    manufacturer: '四川天华节能热工设备公司',
    responsiblePerson: '廖建军',
    contactPhone: '137-8109-1122',
    description: '电缆无氧铜线坯盘料批量退火炉，低氮燃烧机组配电助推循环风机。',
  },
]
