export interface NavigationMenuItem {
  id: string
  systemKey: 'zero-carbon' | 'carbon-footprint'
  systemName: '零碳园区集控中心' | '产品碳足迹集采中心'
  title: string
  route: string
  iconName: string
  level: 1 | 2
  parentId?: string
  parentTitle?: string
  sortOrder: number
  status: '启用' | '停用'
  actions: string[]
  actionCodes?: string[]
  desc?: string
}

export const INITIAL_NAVIGATION_MENUS: NavigationMenuItem[] = [
  /* =========================================================================
   * 1. 零碳园区集控中心 (Park Centralized Control Center)
   * ========================================================================= */
  // 一级模块 1: 集控中心大屏
  {
    id: 'zc_m_screen',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '集控中心大屏',
    route: '/zero-carbon/screen',
    iconName: 'LayoutDashboard',
    level: 1,
    sortOrder: 1,
    status: '启用',
    actions: ['查看大屏', '全屏呈现', '园区切换', '指标联动'],
    desc: '集团级与园区级实时可视化指挥与监控大屏',
  },
  {
    id: 'zc_p_screen_pano',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '全景环幕大屏',
    route: '/zero-carbon/screen',
    iconName: 'Maximize2',
    level: 2,
    parentId: 'zc_m_screen',
    parentTitle: '集控中心大屏',
    sortOrder: 1,
    status: '启用',
    actions: ['查看大屏', '3D场景漫游', '园区切换', '全屏呈现'],
    desc: '集团全景环幕式多维监控与指挥中枢',
  },
  {
    id: 'zc_p_screen_ctrl',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '综合集控大屏 (16:9)',
    route: '/screen/control-center',
    iconName: 'Gauge',
    level: 2,
    parentId: 'zc_m_screen',
    parentTitle: '集控中心大屏',
    sortOrder: 2,
    status: '启用',
    actions: ['查看大屏', '指标联动', '告警快报', '全屏切换'],
    desc: '标准16:9比例指挥控制中心综合大屏',
  },

  // 一级模块 2: 集中监管
  {
    id: 'zc_m_monitor',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '集中监管',
    route: '/zero-carbon/monitor',
    iconName: 'MonitorCog',
    level: 1,
    sortOrder: 2,
    status: '启用',
    actions: ['查看看板', '数据导出', '参数联动', '异常处置'],
    desc: '园区用能、设备与微电网核心实时监测枢纽',
  },
  {
    id: 'zc_p_indicator',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '指标管控',
    route: '/zero-carbon/monitor/indicator',
    iconName: 'BarChart3',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 1,
    status: '启用',
    actions: ['查看看板', '数据导出', '指标下钻', '工序能效分析', '型号明细透视'],
    desc: '企业组织与关键制造工序10项核心管控指标',
  },
  {
    id: 'zc_p_usage',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '用能监测',
    route: '/zero-carbon/monitor/online/usage',
    iconName: 'Activity',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 2,
    status: '启用',
    actions: ['查看监测', '介质切换', '走势图切换', '数据表导出', '时序对比'],
    desc: '全厂水、电、气、热等8大能源介质实时监测',
  },
  {
    id: 'zc_p_equipment',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '重点用能设备',
    route: '/zero-carbon/monitor/online/equipment',
    iconName: 'Cpu',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 3,
    status: '启用',
    actions: ['查看设备', '工况参数拉取', '耗电分析', '蒸汽消耗量监测', '报表导出'],
    desc: '变压器烘房、线缆交联机等重点设备工况监测',
  },
  {
    id: 'zc_p_microgrid',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '工业微电网监测',
    route: '/zero-carbon/monitor/online/microgrid',
    iconName: 'Zap',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 4,
    status: '启用',
    actions: ['功率监测', '电量分析', '绿电消纳', '绿证凭据录入', '台账导出'],
    desc: '园区屋顶分布式光伏、储能充放电与源网荷储平衡',
  },
  {
    id: 'zc_p_carbon_emission',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '能源碳排放监测',
    route: '/zero-carbon/monitor/carbon-emission',
    iconName: 'Leaf',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 5,
    status: '启用',
    actions: ['实时碳排查看', '碳排趋势图表', '经营单位明细', '碳因子基准核算', '明细导出'],
    desc: '范围一、范围二化石与购入电力碳排实时监测',
  },
  {
    id: 'zc_p_custom',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '自定义指标监测',
    route: '/zero-carbon/monitor/custom',
    iconName: 'Sliders',
    level: 2,
    parentId: 'zc_m_monitor',
    parentTitle: '集中监管',
    sortOrder: 6,
    status: '启用',
    actions: ['指标卡片轮播', '自定义指标检索', '走势图切换', '明细台账查看', 'CSV导出'],
    desc: '柔性自定义工况与自设能效参数指标卡片监测',
  },

  // 一级模块 3: 能耗能效分析
  {
    id: 'zc_m_energy',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '能耗能效分析',
    route: '/zero-carbon/energy',
    iconName: 'Gauge',
    level: 1,
    sortOrder: 3,
    status: '启用',
    actions: ['能效分析', '单耗对标', '数据透视', '分析报表导出'],
    desc: '多维度能耗结构拆解与单位产品、产值单耗横向对标',
  },
  {
    id: 'zc_p_structure',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '用能结构分析',
    route: '/zero-carbon/energy/structure',
    iconName: 'PieChart',
    level: 2,
    parentId: 'zc_m_energy',
    parentTitle: '能耗能效分析',
    sortOrder: 1,
    status: '启用',
    actions: ['用能结构查看', '能源成本看板', '介质占比分析', '综合能耗折标', '报表导出'],
    desc: '各能源介质占比结构及用能成本分时段构成分析',
  },
  {
    id: 'zc_p_unit_product',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '单位产品能耗',
    route: '/zero-carbon/energy/unit-product',
    iconName: 'Factory',
    level: 2,
    parentId: 'zc_m_energy',
    parentTitle: '能耗能效分析',
    sortOrder: 2,
    status: '启用',
    actions: ['变压器产业单耗', '线缆产业单耗', '主要产品分类', '型号单耗下钻', '报表导出'],
    desc: '变压器（万kVA/台）与线缆（万km·mm²）单位产品物理单耗分析',
  },
  {
    id: 'zc_p_unit_output',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '单位产值能耗',
    route: '/zero-carbon/energy/unit-output',
    iconName: 'TrendingUp',
    level: 2,
    parentId: 'zc_m_energy',
    parentTitle: '能耗能效分析',
    sortOrder: 3,
    status: '启用',
    actions: ['万元产值单耗', '介质单耗卡片', '时序变化走势', '对标偏差分析', '报表导出'],
    desc: '万元工业总产值/工业增加值能耗强度指标跟踪',
  },
  {
    id: 'zc_p_benchmark',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '对标管理',
    route: '/zero-carbon/energy/benchmark',
    iconName: 'BarChart',
    level: 2,
    parentId: 'zc_m_energy',
    parentTitle: '能耗能效分析',
    sortOrder: 4,
    status: '启用',
    actions: ['工序能耗对标', '先进值对标', '准入值核查', '行业标杆对比', '对标报表导出'],
    desc: '国家标准、行业先进准入值与同行领跑者综合能耗对标',
  },

  // 一级模块 4: 零碳项目评估
  {
    id: 'zc_m_project',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '零碳项目评估',
    route: '/zero-carbon/project',
    iconName: 'ClipboardCheck',
    level: 1,
    sortOrder: 4,
    status: '启用',
    actions: ['项目建档', '运行监测', '效益评估', '自评自测', '评估导出'],
    desc: '技改节能量、储能光伏热泵效益评估与零碳工厂自评估',
  },
  {
    id: 'zc_p_archive',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '项目档案管理',
    route: '/zero-carbon/project/archive',
    iconName: 'FileArchive',
    level: 2,
    parentId: 'zc_m_project',
    parentTitle: '零碳项目评估',
    sortOrder: 1,
    status: '启用',
    actions: ['项目建档查看', '技改工程录入', '效益测算', '档案归档', '清单导出'],
    desc: '全集团节能技改工程全生命周期档案与审批流程管理',
  },
  {
    id: 'zc_p_monitoring',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '实时监控',
    route: '/zero-carbon/project/monitoring',
    iconName: 'MonitorCheck',
    level: 2,
    parentId: 'zc_m_project',
    parentTitle: '零碳项目评估',
    sortOrder: 2,
    status: '启用',
    actions: ['设备运行监控', '储能实时监控', '光伏发电监控', '热泵机组监控', '空调运行监控'],
    desc: '储能电站、分布式光伏、地源热泵与暖通空调运行监控',
  },
  {
    id: 'zc_p_benefit',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '项目运行评估',
    route: '/zero-carbon/project/benefit',
    iconName: 'Coins',
    level: 2,
    parentId: 'zc_m_project',
    parentTitle: '零碳项目评估',
    sortOrder: 3,
    status: '启用',
    actions: ['储能运行评估', '光伏运行评估', '热泵运行评估', '空调运行评估', '效益测算报告'],
    desc: '四大新能源与节能专项工程经济收益与节能量测算评估',
  },
  {
    id: 'zc_p_self',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '零碳工厂自评估',
    route: '/zero-carbon/project/self',
    iconName: 'Award',
    level: 2,
    parentId: 'zc_m_project',
    parentTitle: '零碳项目评估',
    sortOrder: 4,
    status: '启用',
    actions: ['指标自评', '评价得分测算', '差距分析诊断', '自评报告生成', '申报资料导出'],
    desc: '依据国家标准 T/CECA-G 0171 实施的零碳工厂等级认证自评估',
  },

  // 一级模块 5: 统计报表
  {
    id: 'zc_m_reports',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '统计报表',
    route: '/zero-carbon/reports',
    iconName: 'FileBarChart',
    level: 1,
    sortOrder: 5,
    status: '启用',
    actions: ['综合报表查看', '时序报表检索', '分项台账下钻', 'Excel批量导出'],
    desc: '能耗、成本与单耗统计报表批量生成与审计核查',
  },
  {
    id: 'zc_p_report_usage',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '用能报表',
    route: '/zero-carbon/reports/usage',
    iconName: 'TableProperties',
    level: 2,
    parentId: 'zc_m_reports',
    parentTitle: '统计报表',
    sortOrder: 1,
    status: '启用',
    actions: ['日/月/年综合报表', '介质分类汇总', '多级组织穿透', 'Excel报表导出'],
    desc: '各厂矿分介质实物用量与折标能耗综合时序明细报表',
  },
  {
    id: 'zc_p_report_cost',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '成本报表',
    route: '/zero-carbon/reports/cost',
    iconName: 'Receipt',
    level: 2,
    parentId: 'zc_m_reports',
    parentTitle: '统计报表',
    sortOrder: 2,
    status: '启用',
    actions: ['分时电度电费', '尖峰平谷成本', '介质支出结算', '成本明细导出'],
    desc: '分时电费、燃气费与外购蒸汽等能源成本结算报表',
  },
  {
    id: 'zc_p_report_unit',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '单耗报表',
    route: '/zero-carbon/reports/unit',
    iconName: 'Percent',
    level: 2,
    parentId: 'zc_m_reports',
    parentTitle: '统计报表',
    sortOrder: 3,
    status: '启用',
    actions: ['单位产品能耗表', '万元产值单耗表', '工序产出单耗表', '单耗台账导出'],
    desc: '主要产品实物单耗、工序综合单耗与万元产值单耗核算报表',
  },

  // 一级模块 6: 企业信息管理
  {
    id: 'zc_m_config_entry',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '企业信息管理',
    route: '/zero-carbon/config/entry',
    iconName: 'Settings2',
    level: 1,
    sortOrder: 6,
    status: '启用',
    actions: ['企业档案查看', '基础信息维护', '产量人工填报', '零碳申报更新'],
    desc: '企业基础台账、排产产量月度人工填报与零碳工厂认证申报',
  },
  {
    id: 'zc_p_entry_basic',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '企业基础信息',
    route: '/zero-carbon/config/entry',
    iconName: 'Building',
    level: 2,
    parentId: 'zc_m_config_entry',
    parentTitle: '企业信息管理',
    sortOrder: 1,
    status: '启用',
    actions: ['企业档案查看', '生产用能基准', '工厂产量填报', '自备能源录入', '历史填报查验'],
    desc: '企业组织基本信息与关键产品产量人工填报台账',
  },
  {
    id: 'zc_p_entry_declare',
    systemKey: 'zero-carbon',
    systemName: '零碳园区集控中心',
    title: '零碳工厂信息',
    route: '/zero-carbon/config/factory-declare',
    iconName: 'FileCheck',
    level: 2,
    parentId: 'zc_m_config_entry',
    parentTitle: '企业信息管理',
    sortOrder: 2,
    status: '启用',
    actions: ['零碳园区申报', '绿电消纳凭证', '工厂能效承诺', '审核状态跟踪'],
    desc: '零碳工厂年度建设成果填报、自我评价与资料声明',
  },

  /* =========================================================================
   * 2. 产品碳足迹集采中心 (Product Carbon Footprint Center)
   * ========================================================================= */
  // 一级模块 1: 对外示范窗口
  {
    id: 'cf_m_cockpit',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '对外示范窗口',
    route: '/carbon-footprint/cockpit',
    iconName: 'LayoutDashboard',
    level: 1,
    sortOrder: 1,
    status: '启用',
    actions: ['查看看板', '态势下钻', '产品碳排筛选', '全屏呈现'],
    desc: '全集团产品碳足迹对外展示与客户溯源驾驶舱',
  },
  {
    id: 'cf_p_cockpit_view',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '碳足迹驾驶舱',
    route: '/carbon-footprint/cockpit',
    iconName: 'Gauge',
    level: 2,
    parentId: 'cf_m_cockpit',
    parentTitle: '对外示范窗口',
    sortOrder: 1,
    status: '启用',
    actions: ['碳足迹大盘', '组织机构碳排', '核心产品碳强度', '供应链碳溯源', '态势深度下钻'],
    desc: '变压器与线缆全生命周期碳排强度对外可视化大盘',
  },

  // 一级模块 2: 多维分析
  {
    id: 'cf_m_analysis',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '多维分析',
    route: '/carbon-footprint/analysis',
    iconName: 'BarChart3',
    level: 1,
    sortOrder: 2,
    status: '启用',
    actions: ['多维对比', '横向对标', '纵向追溯', '分析报告导出'],
    desc: '跨基地、跨批次及全生命周期碳排放横向与纵向深度对比',
  },
  {
    id: 'cf_p_compare',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '横向对比',
    route: '/carbon-footprint/analysis/compare',
    iconName: 'GitCompare',
    level: 2,
    parentId: 'cf_m_analysis',
    parentTitle: '多维分析',
    sortOrder: 1,
    status: '启用',
    actions: ['同类产品对比', '跨工厂碳足迹', '行业先进对标', '碳差距分析', '分析报告导出'],
    desc: '不同基地同规格变压器/线缆单位产品碳足迹横向比对',
  },
  {
    id: 'cf_p_ranking',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '纵向对比',
    route: '/carbon-footprint/analysis/ranking',
    iconName: 'TrendingDown',
    level: 2,
    parentId: 'cf_m_analysis',
    parentTitle: '多维分析',
    sortOrder: 2,
    status: '启用',
    actions: ['历史生命周期走势', '年度减碳成效', '工艺工序拆解', '工序能碳下钻', '趋势报告导出'],
    desc: '同产品型号在不同生命周期批次及年份中的碳减排演进追踪',
  },

  // 一级模块 3: 实景数据库
  {
    id: 'cf_m_database',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '实景数据库',
    route: '/carbon-footprint/database',
    iconName: 'Database',
    level: 1,
    sortOrder: 3,
    status: '启用',
    actions: ['实景台账查看', '碳足迹核算', '核算模型发布', '碳报告生成', '数据库导出'],
    desc: 'BOM物料实景碳排放源、工艺阶段核算与碳足迹核算模型',
  },
  {
    id: 'cf_p_realscene',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '实景数据库',
    route: '/carbon-footprint/database/realscene',
    iconName: 'DatabaseZap',
    level: 2,
    parentId: 'cf_m_database',
    parentTitle: '实景数据库',
    sortOrder: 1,
    status: '启用',
    actions: ['实景台账查看', '物料BOM实采', '供应商碳因子', '实景数据校验', '数据库导出'],
    desc: '产品BOM级原材料消耗、物料溯源与现场工况实测数据库',
  },
  {
    id: 'cf_p_accounting',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '碳足迹核算',
    route: '/carbon-footprint/database/accounting',
    iconName: 'Calculator',
    level: 2,
    parentId: 'cf_m_database',
    parentTitle: '实景数据库',
    sortOrder: 2,
    status: '启用',
    actions: ['LCA全生命周期核算', '核算模型配置', '工序能耗分配', '碳排结果计算', '核算基准发布'],
    desc: '摇篮到大门（Cradle-to-Gate）LCA阶段能耗分配与碳足迹核算',
  },
  {
    id: 'cf_p_db_report',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '碳足迹报告',
    route: '/carbon-footprint/database/report',
    iconName: 'FileSpreadsheet',
    level: 2,
    parentId: 'cf_m_database',
    parentTitle: '实景数据库',
    sortOrder: 3,
    status: '启用',
    actions: ['ISO 14067标准报告', 'CBAM合规报告', '第三方鉴证底稿', '报告在线生成', 'PDF/Excel归档'],
    desc: '符合国际标准的单件产品生命周期碳足迹核算报告生成与归档',
  },

  // 一级模块 4: CBAM管理
  {
    id: 'cf_m_cbam',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: 'CBAM管理',
    route: '/carbon-footprint/cbam',
    iconName: 'ShieldCheck',
    level: 1,
    sortOrder: 4,
    status: '启用',
    actions: ['合规管理', '申报模拟', '知识库管理', '碳关税预警', '报表导出'],
    desc: '欧盟碳边境调节机制（CBAM）出海合规自查与申报模拟',
  },
  {
    id: 'cf_p_compliance',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '合规管理',
    route: '/carbon-footprint/cbam/compliance',
    iconName: 'ShieldAlert',
    level: 2,
    parentId: 'cf_m_cbam',
    parentTitle: 'CBAM管理',
    sortOrder: 1,
    status: '启用',
    actions: ['欧盟CBAM台账', '海关税则HS编码', '直接与间接排放', '合规自查校验', '合规档案导出'],
    desc: '钢铁、铝材等CBAM管控目录商品出口海关合规台账审计',
  },
  {
    id: 'cf_p_declaration',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '申报模拟',
    route: '/carbon-footprint/cbam/declaration',
    iconName: 'Calculator',
    level: 2,
    parentId: 'cf_m_cbam',
    parentTitle: 'CBAM管理',
    sortOrder: 2,
    status: '启用',
    actions: ['出海碳关税测算', '隐含碳排放核算', '欧盟碳价模拟', '申报表格导出', '预警评估'],
    desc: '基于欧盟最新ETS碳配额价格的出海产品碳关税测算与申报模拟',
  },
  {
    id: 'cf_p_knowledge',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '知识库',
    route: '/carbon-footprint/cbam/knowledge',
    iconName: 'BookOpen',
    level: 2,
    parentId: 'cf_m_cbam',
    parentTitle: 'CBAM管理',
    sortOrder: 3,
    status: '启用',
    actions: ['欧盟政策法规', '默认排放因子表', '计算方法指南', '最新法案查阅', '知识库维护'],
    desc: '欧盟官方法规条款、默认值参考库与通关填报指导手册',
  },

  // 一级模块 5: 第三方认证管理
  {
    id: 'cf_m_certification',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '第三方认证管理',
    route: '/carbon-footprint/certification',
    iconName: 'BadgeCheck',
    level: 1,
    sortOrder: 5,
    status: '启用',
    actions: ['资料维护', '认证申请', '审核跟踪', '证书结果录入', '证书导出'],
    desc: 'SGS、TÜV、中国质量认证中心（CQC）等第三方认证流程与证书台账',
  },
  {
    id: 'cf_p_material',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '认证资料维护',
    route: '/carbon-footprint/certification/material',
    iconName: 'FolderArchive',
    level: 2,
    parentId: 'cf_m_certification',
    parentTitle: '第三方认证管理',
    sortOrder: 1,
    status: '启用',
    actions: ['认证资料清单', '企业资质上传', '检测报告归档', '第三方机构关联', '资料包打包下载'],
    desc: '送审产品BOM清单、能源账单发票与原材料供应商凭据维护',
  },
  {
    id: 'cf_p_apply',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '认证申请',
    route: '/carbon-footprint/certification/apply',
    iconName: 'Send',
    level: 2,
    parentId: 'cf_m_certification',
    parentTitle: '第三方认证管理',
    sortOrder: 2,
    status: '启用',
    actions: ['发起认证申请', '认证机构委派', '现场审核预约', '审核进度跟踪', '费用结算管理'],
    desc: '向认证机构在线提报申请、验厂排期与审核状态流转',
  },
  {
    id: 'cf_p_result',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '认证结果管理',
    route: '/carbon-footprint/certification/result',
    iconName: 'Award',
    level: 2,
    parentId: 'cf_m_certification',
    parentTitle: '第三方认证管理',
    sortOrder: 3,
    status: '启用',
    actions: ['碳中和证书登记', '碳足迹声明查验', '证书有效期预警', '证书真伪扫码', '证书下载与分发'],
    desc: '正式碳足迹核查证书、声明证书电子档案登记与有效期预警',
  },

  // 一级模块 6: 因子库管理
  {
    id: 'cf_m_factor',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '因子库管理',
    route: '/carbon-footprint/factor',
    iconName: 'Boxes',
    level: 1,
    sortOrder: 6,
    status: '启用',
    actions: ['因子检索', '因子新增', '版本维护', '停用废止', '批量导入导出'],
    desc: '原材料、区域电网、化石能源碳排放因子与折标煤系数库',
  },
  {
    id: 'cf_p_factor_material',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '原材料碳排因子',
    route: '/carbon-footprint/factor/material',
    iconName: 'Layers',
    level: 2,
    parentId: 'cf_m_factor',
    parentTitle: '因子库管理',
    sortOrder: 1,
    status: '启用',
    actions: ['铜杆/铝材/绝缘纸因子', '上游供应链因子', '自定义因子录入', '因子版本管理', '因子库检索导出'],
    desc: '铜、铝、硅钢片、环氧树脂等大宗工业原材料排放因子库',
  },
  {
    id: 'cf_p_factor_power',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '电力碳排因子',
    route: '/carbon-footprint/factor/power',
    iconName: 'Zap',
    level: 2,
    parentId: 'cf_m_factor',
    parentTitle: '因子库管理',
    sortOrder: 2,
    status: '启用',
    actions: ['全国区域电网因子', '省域电网基准', '绿电零碳折算', '因子有效账期', '批量导入导出'],
    desc: '国家生态环境部与发改委发布的全国与省级电网平均碳排因子',
  },
  {
    id: 'cf_p_factor_energy',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '能源活动碳排因子',
    route: '/carbon-footprint/factor/energy',
    iconName: 'Flame',
    level: 2,
    parentId: 'cf_m_factor',
    parentTitle: '因子库管理',
    sortOrder: 3,
    status: '启用',
    actions: ['天然气/蒸汽/柴油碳因子', '单位热值含碳量', '碳氧化率维护', '国家标准同步', '因子校验'],
    desc: '天然气、外购蒸汽、柴油、汽油等一次/二次能源直接排放因子',
  },
  {
    id: 'cf_p_factor_coal',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '折标煤系数库',
    route: '/carbon-footprint/factor/coal',
    iconName: 'Sparkles',
    level: 2,
    parentId: 'cf_m_factor',
    parentTitle: '因子库管理',
    sortOrder: 4,
    status: '启用',
    actions: ['等价折标煤系数', '当量折标煤系数', '介质折算规则', '行业系数对比', '系数库导出'],
    desc: 'GB/T 2589 综合能耗计算通则法定折标准煤物理换算系数库',
  },

  // 一级模块 7: 基础配置
  {
    id: 'cf_m_config',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '基础配置',
    route: '/carbon-footprint/config',
    iconName: 'Settings2',
    level: 1,
    sortOrder: 7,
    status: '启用',
    actions: ['GWP潜能值配置', '供应链核算边界', '生命周期参数设置', '参数发布'],
    desc: 'GWP全球变暖潜能值、生命周期截止准则与供应链核算边界配置',
  },
  {
    id: 'cf_p_config_base',
    systemKey: 'carbon-footprint',
    systemName: '产品碳足迹集采中心',
    title: '基础参数配置',
    route: '/carbon-footprint/config',
    iconName: 'SlidersHorizontal',
    level: 2,
    parentId: 'cf_m_config',
    parentTitle: '基础配置',
    sortOrder: 1,
    status: '启用',
    actions: ['GWP全球变暖潜能值', '产品型号生命周期', '供应链核算边界', '系统参数设置'],
    desc: 'IPCC第六次评估报告GWP基准值及计算规则统一配置',
  },
]
